version: '3'

services:
  myapp:
    image: infracloudio/csvserver:latest
    ports:
      - "9393:9300"
    env_file:
      - ./env
    volumes:
      - ./inputFile:/csvserver/inputdata

  prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    volumes:
      - /root/csvserver/solution/prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
